### ISSUE TITLE
Random Shape Image Generator

### ISSUE THREAD

**Issue by akash-rajak** [mayankchaudhary26/Hacktober-2021#217]
In this will create a tkinter based GUI 
Using this user will be able to create image with random geometry shapes.

**Comment by akash-rajak** [comment]
@mayankchaudhary26 can i work on this under hacktoberfest?

**Comment by khushboorathore10** [comment]
Hi I want to work on this issue..Please assign me this issue @akash435 @mayankchaudhary26

**Comment by khushboorathore10** [comment]
Added Random Image Generator ...Checkout #278

**Comment by akash-rajak** [comment]
@khushboorathore10 , this project got excluded from hacktoberfest.
Like my PR also go excluded.

you can see here
![image](https://user-images.githubusercontent.com/57003737/135964678-9d5c9d73-f81b-4285-a35f-c764df2d2753.png)

**Comment by mayankchaudhary26** [comment]
Unlike every year, Hacktoberfest has changed its guideline.

Some examples of projects that don’t follow the values of Hacktoberfest include:

Projects asking contributors to submit assorted data structures and algorithms (DSA)
Projects asking contributors to curate arbitrary lists of quotes, interview questions, etc.
WE'VE IMPLEMENTED A SYSTEM TO BLOCK THESE REPOSITORIES, AND ANY PULL REQUESTS SUBMITTED TO SUCH REPOSITORIES WILL NOT BE COUNTED.

That's why
