### ISSUE TITLE
Pull request(s) not counted

### ISSUE THREAD

**Issue by sahillangoo** [mayankchaudhary26/Hacktober-2021#291]
Got this error from https://hacktoberfest.digitalocean.com/profile
``` This pull request was submitted to a repository that does not follow the values of Hacktoberfest, so has been excluded. No pull requests to this repository will be counted for Hacktoberfest.```

**Comment by mayankchaudhary26** [comment]
Unlike every year, Hacktoberfest has changed its guideline.

Some examples of projects that don’t follow the values of Hacktoberfest include:

**Projects asking contributors to submit assorted data structures and algorithms (DSA)
Projects asking contributors to curate arbitrary lists of quotes, interview questions, etc.
WE'VE IMPLEMENTED A SYSTEM TO BLOCK THESE REPOSITORIES, AND ANY PULL REQUESTS SUBMITTED TO SUCH REPOSITORIES WILL NOT BE COUNTED.**



That's why our repositories aren't valid any more :((
